sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - IMAGE_NAME=janerz6/accommodations:0.7.2
install:
- mvn clean package -U

after_success:
- docker login -u="janerz6" -p=$DOCKER_PASSWORD
- docker build -t $IMAGE_NAME .
- docker push $IMAGE_NAME