sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

install:
- mvn clean package -U

after_success:
- docker login -u="janerz6" -p="dockerRSO"
- docker build -t janerz6/accommodations .
- docker push $REPO