sudo: required
services:
- docker
language: java
dist: trusty
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
install:

scripts:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- docker build -t janerz6/accommodations .
after_success:
- docker login -u="janerz6" -p="dockerRSO"
- docker push janerz6/accommodations