apiVersion: v1
kind: Service
metadata:
  name: accommodations
  labels:
    app: accommodations
spec:
  type: NodePort
  ports:
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accommodations
