apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: accommodations-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: accommodations
    spec:
      containers:
      - image: janerz6/accommodations:0.7.3
        name: accommodations
        env:
          - name: CONFIG_SERVER_URL
            value: consul
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 40
          periodSeconds: 3
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: accommodations
  labels:
    app: accommodations
spec:
  type: NodePort
  ports:
  - name: server
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: accommodations
